# Generated by Django 3.2 on 2021-04-23 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории продуктов')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('obl', models.CharField(max_length=255, verbose_name='Ваш регион')),
                ('who', models.CharField(choices=[('Производитель', 'Производитель'), ('Поставщик', 'Поставщик')], default='Поставщик', max_length=255, verbose_name='Статус пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(verbose_name='Продукт')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер телефона:')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Предлагаемая цена')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий:')),
                ('status', models.IntegerField(verbose_name='Количество просмотров')),
                ('to_user', models.IntegerField(verbose_name='Кому')),
                ('from_user', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Ptoduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(verbose_name='Автор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('photo', models.ImageField(upload_to='product/', verbose_name='Фотография продукта')),
                ('info', models.TextField(verbose_name='Описание услуги')),
                ('status', models.CharField(choices=[('Производитель', 'Производитель'), ('Поставщик', 'Поставщик')], default='Производитель', max_length=255, verbose_name='От кого')),
                ('reg', models.CharField(max_length=255, verbose_name='Регион')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена на услугу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='obsluzh.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.myuser')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to='obsluzh.Order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.myuser')),
            ],
            options={
                'verbose_name': 'Лист заказов',
                'verbose_name_plural': 'Листы заказов',
            },
        ),
    ]
