# Generated by Django 3.2 on 2021-04-21 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории продуктов')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('price_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль для прайс-листа')),
                ('who', models.CharField(choices=[('Покупатель', 'Покупатель'), ('Продавец', 'Продавец')], default='Покупатель', max_length=255, verbose_name='Статус пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона:')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Предварительная цена')),
                ('status', models.CharField(choices=[('Запланирован', 'Запланирован'), ('Отменен', 'Отменен'), ('Готов', 'Готов')], default='Запланирован', max_length=255, verbose_name='статус')),
                ('hour', models.CharField(max_length=2, verbose_name='Час')),
                ('day', models.CharField(max_length=2, verbose_name='День')),
                ('mounth', models.CharField(max_length=10, verbose_name='Месяц')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий:')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Ptoduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена на продукт')),
                ('opt_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Оптовая цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='obsluzh.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.myuser')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(to='obsluzh.Order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsluzh.myuser')),
            ],
            options={
                'verbose_name': 'Лист заказов',
                'verbose_name_plural': 'Листы заказов',
            },
        ),
    ]
